apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_NAME: cmVzdGF1cmFudGRi  # base64 encoded value of "restaurantdb"
  DB_USER: QWhtZWQ=  # base64 encoded value of "Ahmed"
  DB_PASS: QWhtZWQxMjM=  # base64 encoded value of "Ahmed123"

